### ISSUE TITLE
Swift Package Manager fails due to Invalid Manifest

### ISSUE THREAD

**Issue by bordsfast** [yonat/CameraBackground#11]
**Version Used:** `1.6.6`
**Note:** 

1. I also tried the master branch and Next Major version with same results
2. Used the XCode interface for adding a package

Sample Screenshot of the issue: 

<img width="1064" alt="Adding package failed" src="https://user-images.githubusercontent.com/17524847/200731586-cc020c3a-179e-49b6-8375-3cc49a958a63.png">

**Comment by yonat** [comment]
Thanks for the report! Fixed in 1.6.7.
