### ISSUE TITLE
landscape position issue

### ISSUE THREAD

**Issue by RanaAbdou** [yonat/CameraBackground#6]
i used the lib in project and make the camera view controller in middle of project and to open it i used 
self.navigationController?.pushViewController(VC, animated: true)
in landscape position (live stream ) the photo was rotated 
any help how to fix this?

**Comment by yonat** [comment]
Sorry, I don't actually use it in landscape. But a PR would be welcome!

**Comment by RanaAbdou** [comment]
Thank you
