### ISSUE TITLE
How to use 'WideAngleCamera' in CameraBackground project

### ISSUE THREAD

**Issue by ghost** [yonat/CameraBackground#7]
Hello Yonat,

I am trying to use WideAngleCamera in CameraBackground. please suggest me how to use WideAngleCamera in project.

Thank you

**Comment by yonat** [comment]
I'm not sure, actually. What problems are you having? What do you see and how it is different than what you want to see?

**Comment by ghost** [comment]
I am trying to use latest iOS version 13.0 AVCaptureDevice.DeviceType like 

1. builtInTripleCamera
2.builtInDualWideCamera
3. builtInUltraWideCamera

please suggest me how to use for take picture from camera. Thank you .

**Comment by yonat** [comment]
This library specify the the device type. What do you see when you run it? Do you have access to the wide camera or not?

**Comment by ghost** [comment]
yes @yonat

**Comment by yonat** [comment]
So what is the problem? I'm not able to see what problem you are trying to solve. Can you explain?

**Comment by ghost** [comment]
Yes, I Want to use Wide Angle Camera in Xcode. i am confused how to use. please suggest me

**Comment by yonat** [comment]
Sorry, I don't have a device with wide camera to try this on, and I can't help you if you don't explain what problems you are seeing.
