### ISSUE TITLE
AddCameraBackground when device is in landscape, camera preview displays portrait orientation

### ISSUE THREAD

**Issue by nastasiupta** [yonat/CameraBackground#8]
**Description of the problem:**
Place the iPhone in landscape orientation.
Call `addCameraBackground` function (position any, show buttons false)

The camera preview layer is not taking into consideration the device orientation. For properly layout, I have to rotate the device in portrait, and then to landscape again.

**Comment by yonat** [comment]
Your'e right, I don't have support for landscape mode yet (no free time to implement it). If you want to add it, I would welcome the PR.
